# Generated by Django 2.2.13 on 2020-08-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20200810_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '图书', 'verbose_name_plural': '图书'},
        ),
    ]
